name: "Set up env vars"
description: "Set up env vars"

runs:
  using: "composite"
  steps:
    - name: Set env
      run: >-
        echo "TAG=${HEAD_TAG::8}" >> ${GITHUB_ENV};
        echo ${HEAD_TAG::8}
      env:
        HEAD_TAG: ${{ github.event.pull_request.head.sha || github.sha }}
      shell: bash
    - name: Downcase repo
      run: |
        echo "REPO_LOWER=${REPO}" >> ${GITHUB_ENV}
      env:
        REPO: "${{ github.repository }}"
      shell: bash
