name: "Set up env vars"
description: "Set up env vars"
inputs:
  image_name:
    required: false
    type: string
  subdir:
    default: '.'
    type: string
  tag:
    required: false
    type: string
  token:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Set env
      run: >-
        echo "TAG=${HEAD_TAG::8}" >> ${GITHUB_ENV};
        echo ${HEAD_TAG::8}
      env:
        HEAD_TAG: ${{ inputs.tag || github.event.pull_request.head.sha || github.sha }}
      shell: bash
    - name: Downcase repo
      env:
        REPO: "${{ inputs.image_name || github.repository }}"
      run: |
        echo "REPO_LOWER=${REPO,,}" >> ${GITHUB_ENV}
      shell: bash
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
        token: ${{ inputs.token }}
        clean: false
    - name: Make sure env files are present if missing
      run: >-
        cd ${{ inputs.subdir }};
        touch .env.development;
        touch .env;
      shell: bash
    - name: Create more disk space # See https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
      if: ${{ github.job != 'deployment' }}
      run: sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      shell: bash
